name: supre_me
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.9
  conditional_builder_null_safety: ^0.0.6
  easy_localization: ^3.0.1
  dio: ^4.0.6
  fluttertoast: ^8.0.8
  internet_connection_checker: ^0.0.1+4
  geolocator: ^9.0.2
  geocoding: ^2.0.2
  google_maps_flutter: ^2.3.0
  image_picker: ^0.8.6
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  audio_session: ^0.1.13
  audioplayers: ^4.1.0
  permission_handler: ^10.2.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  path: ^1.8.2
  cached_network_image: ^3.2.3





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

