// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: 'AIzaSyD8mqzcK5UdxBw-7-XVPeKjABaZd2qudMg',
//       appId: '1:550104170052:android:333677e582738766900611',
//       messagingSenderId: '550104170052',
//       projectId: 'uclinics-eda21',
//       storageBucket: 'uclinics-eda21.appspot.com',
//       androidClientId: '550104170052-8812b49uugs7g0l11gqhrcj8ok9qm4j5.apps.googleusercontent.com',
//      // deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: 'AIzaSyB5pFzIyKt3OpuPokZZH8HT_oQJ2WDA1is',
//       appId: '1:550104170052:ios:88da50047e314401900611',
//       messagingSenderId: '550104170052',
//       projectId: 'uclinics-eda21',
//       storageBucket: 'uclinics-eda21.appspot.com',
//       iosClientId: '550104170052-vbn37j6g7t1s7cisgrlfvnptdpgp7p00.apps.googleusercontent.com',
//       iosBundleId: 'com.uclinics',
//    //   deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
// }
